//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for NHibernate model.
// Code is generated on: 7/3/2024 11:35:49
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using NHibernate;
using NHibernate.Linq;

namespace DAO
{
    public partial class ConfiguracionesRepository : NHibernateRepository<Domain.Configuraciones>, IConfiguracionesRepository
    {
        public ConfiguracionesRepository(ISession session) : base(session)
        {
        }

        public virtual Domain.Configuraciones GetFirst()
        {
            return session.CreateQuery(string.Format("from Configuraciones")).SetMaxResults(1).UniqueResult<Domain.Configuraciones>();
        }

        public virtual Domain.Configuraciones GetByKey(int _Id)
        {
            return session.Get<Domain.Configuraciones>(_Id);
        }
    }
}
