//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 5/3/2024 17:22:17
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Domain
{

    /// <summary>
    /// There are no comments for Domain.Clientes, Domain in the schema.
    /// </summary>
    public partial class Clientes {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Clientes constructor in the schema.
        /// </summary>
        public Clientes()
        {
            this.Turnos = new HashSet<Turnos>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nombre in the schema.
        /// </summary>
        public virtual string Nombre
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Apellido in the schema.
        /// </summary>
        public virtual string Apellido
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Email in the schema.
        /// </summary>
        public virtual string Email
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Telefono in the schema.
        /// </summary>
        public virtual string Telefono
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Observaciones in the schema.
        /// </summary>
        public virtual string Observaciones
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FechaAlta in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaAlta
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Activo in the schema.
        /// </summary>
        public virtual System.Nullable<bool> Activo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdTelefonoTipo in the schema.
        /// </summary>
        public virtual System.Nullable<int> IdTelefonoTipo
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Usuario in the schema.
        /// </summary>
        public virtual Usuario Usuario
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Turnos in the schema.
        /// </summary>
        public virtual ISet<Turnos> Turnos
        {
            get;
            set;
        }
    }

}
