//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 5/3/2024 17:22:17
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Domain
{

    /// <summary>
    /// There are no comments for Domain.FechaTurnos, Domain in the schema.
    /// </summary>
    public partial class FechaTurnos {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for FechaTurnos constructor in the schema.
        /// </summary>
        public FechaTurnos()
        {
            this.Turnos = new HashSet<Turnos>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FechaTurno in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaTurno
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Turnos in the schema.
        /// </summary>
        public virtual ISet<Turnos> Turnos
        {
            get;
            set;
        }
    }

}
