//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 1/3/2024 16:43:22
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace Domain
{

    /// <summary>
    /// There are no comments for Domain.Turnos, Domain in the schema.
    /// </summary>
    public partial class Turnos {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Turnos constructor in the schema.
        /// </summary>
        public Turnos()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nombre in the schema.
        /// </summary>
        public virtual string Nombre
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Apellido in the schema.
        /// </summary>
        public virtual string Apellido
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for NroTelefono in the schema.
        /// </summary>
        public virtual System.Nullable<int> NroTelefono
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Diseño in the schema.
        /// </summary>
        public virtual string Diseño
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Clientes in the schema.
        /// </summary>
        public virtual Clientes Clientes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FechaTurnos in the schema.
        /// </summary>
        public virtual FechaTurnos FechaTurnos
        {
            get;
            set;
        }
    }

}
